### ISSUE TITLE
Something to do with SQL_MODE

### ISSUE THREAD

**Issue by digammavauf** [IndomaximTechID/storaji-ui#5] opened 2018-04-29 03:39 UTC
<p>after running <code>'php artisan migrate'</code></p>
<pre>  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'image' can't have a de
  fault value (SQL: alter table `products` add `image` text not null default 'data:image/svg+...</pre>
<p>THIS IS FOR THE API-side</p>
<p>I only did what I did below to force a success in migration and to see the app...</p>
<pre>class AddImageToProductTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->nullable();
            // $table->text('image')->default('data:image/svg+xml,%3C%21DOCTYPE%20svg%20PUBLIC%20%22-//W3C//DTD%20SVG%2020010904//EN%22%20%22http%3A//www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd&nbsp;
...
&nbsp;/g%3E%0A%0A%3C/svg%3E');
        });
    }</pre>
<p>I comment out <code>->text('image')->default()</code> and add <code>->nullable();</code></p>
<p>...and finally, re-running <code>php artisan migrate</code> gives me:</p>
<pre>Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
...
Migrated:  2018_01_13_172936_add_soft_deletes_to_order_table
Migrating: 2018_01_13_182222_add_image_to_product_table
Migrated:  2018_01_13_182222_add_image_to_product_table</p>

**Comment by eriestrisnadi** [comment] 2018-05-01 12:39
@digammavauf duplicate of https://github.com/IndomaximTechID/storaji/issues/15

**Closed as completed by eriestrisnadi** 2018-05-01 12:39 UTC
